### ISSUE TITLE
Streaming Efficient Conformer isn't working

### ISSUE THREAD

**Issue by Uncomfy** [wenet-e2e/wenet#1690]
I was able to reproduce the Efficient Conformer model using the scripts provided in the AIShell example. If I run the decoding using "recognize.py" with "decoding_chunk_size" set to 16 I'm able to reproduce the numbers reported by you, but if I add "simulate_streaming" flag or try to use this model in the runtime - CER jumps to almost 50%.

Is Efficient Conformer just not designed for streaming?

**Comment by robin1001** [comment]
@zwglory , please follow the issue.

**Comment by zwglory** [comment]
If you want a streaming model, `causal: true` needs to be specified when training the model.

In addition, `decoding_chunk_size ` is best set to a common multiple of `group_size`. If group_size=3, then `decoding_chunk_size` can be 18.


```
encoder: efficientConformer
encoder_conf:
    activation_type: 'swish'
    attention_heads: 8
    causal: true
    cnn_module_kernel: 15
    cnn_module_norm: 'layer_norm'
    dropout_rate: 0.1
    input_layer: conv2d
    linear_units: 2048
    normalize_before: true
    num_blocks: 12
    output_size: 256
    pos_enc_layer_type: 'rel_pos'
    attention_dropout_rate: 0.1
    positional_dropout_rate: 0.1
    use_cnn_module: true
    use_dynamic_chunk: true
    use_dynamic_left_chunk: false
    efficient_conf:
        stride_layer_idx: [3]           # layer id with StrideConv
        stride: [2]                     # stride size of each StrideConv
        group_layer_idx: [0, 1, 2, 3]   # layer id with GroupedAttention
        group_size: 3                   # group size of every GroupedAttention layer
        stride_kernel: true             # true: recompute cnn kernels with stride
```
